# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
    hooks:
        - go mod tidy

archives:
    - id: default
      ids:
          - armoctl
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    - id: binaries
      ids:
          - armoctl
      formats:
          - binary
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

builds:
    - id: armoctl
      main: .
      binary: armoctl
      ldflags:
          - -X main.version={{ .Version }}
          - -X main.commit={{ .ShortCommit }}
          - -X main.buildTime={{ .Date }}
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
      goarch:
          - amd64
          - arm64

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    draft: true
    footer: >-

        ---

        Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
